# Generated by Django 5.2.7 on 2025-10-24 21:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.CharField(max_length=200)),
                ('contract_no', models.CharField(blank=True, max_length=200)),
                ('assigned_location', models.CharField(blank=True, max_length=255)),
                ('project_title', models.CharField(blank=True, max_length=500)),
                ('team', models.CharField(blank=True, max_length=200)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('prepared_by', models.CharField(blank=True, max_length=200)),
                ('client_rep', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('company', models.CharField(default='STIS', max_length=100)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='timesheet.timesheet')),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('discipline', models.CharField(blank=True, max_length=200)),
                ('attendance', models.JSONField(blank=True, default=dict)),
                ('total', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timesheet.timesheet')),
            ],
        ),
    ]
