# Generated by Django 5.2.7 on 2025-10-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
